# Generated by Django 5.1.3 on 2024-12-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_event_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата мероприятия'),
        ),
    ]
